// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDieL58i0Go3Ah54kRTbwNaY9VF_O8ZOfI',
    appId: '1:1090347003063:web:bbf32340fc83b26675b132',
    messagingSenderId: '1090347003063',
    projectId: 'geminai-realms-8c93a',
    authDomain: 'geminai-realms-8c93a.firebaseapp.com',
    storageBucket: 'geminai-realms-8c93a.appspot.com',
    measurementId: 'G-YD6K44T1PB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkTM5pM1GvxWrOYC34FIWIjmEIyZv_vB4',
    appId: '1:1090347003063:android:f6f2395236888dfd75b132',
    messagingSenderId: '1090347003063',
    projectId: 'geminai-realms-8c93a',
    storageBucket: 'geminai-realms-8c93a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmjul6-QvD2R4EGxGOupEjqzUJ-Y1WC1U',
    appId: '1:1090347003063:ios:68af4764545b013f75b132',
    messagingSenderId: '1090347003063',
    projectId: 'geminai-realms-8c93a',
    storageBucket: 'geminai-realms-8c93a.appspot.com',
    iosBundleId: 'com.example.geminaiRealms',
  );
}
